import ThemeRegister from '@/components/ThemeRegister'
import { Providers } from '@/redux/Providers';
import {store} from '@/redux/store';
import { useMediaQuery } from '@mui/material';
import type { Metadata } from 'next'
import { useMemo } from 'react';
import { Provider } from 'react-redux';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <Providers >
          <ThemeRegister>

            {children}

          </ThemeRegister>
        </Providers>
      </body>
    </html>
  )
}
