import ThemeRegister from '@/components/ThemeRegister'
import { Providers } from '@/redux/Providers';
import { store } from '@/redux/store';
import { useMediaQuery } from '@mui/material';
import type { Metadata } from 'next'
import { PropsWithChildren, useMemo } from 'react';
import { Provider } from 'react-redux';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface LayoutProps extends PropsWithChildren<{}> {

}

export default function RootLayout(props: LayoutProps) {

  const { children, } = props;

  return (
    <html lang="en">
      <body>
        <Providers >
          <ThemeRegister>

            {children}

          </ThemeRegister>
        </Providers>
      </body>
    </html>
  )
}
